# Generated by Django 4.1 on 2023-06-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
