# Generated by Django 4.1 on 2023-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0004_alter_journal_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
