# Generated by Django 4.1 on 2023-06-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0005_paper_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
