# Generated by Django 4.1 on 2023-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0006_alter_issue_number_alter_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='institution',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
