# Generated by Django 4.1 on 2023-06-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0007_paper_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='recieved',
            field=models.DateField(null=True),
        ),
    ]
