# Generated by Django 4.1 on 2023-06-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0009_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='supplementary',
        ),
    ]
