# Generated by Django 4.1 on 2023-06-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0010_remove_submission_manuscript_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
