# Generated by Django 4.1 on 2023-06-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0012_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
