# Generated by Django 4.1 on 2023-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0014_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='manuscript',
            field=models.FileField(upload_to='papers/%Y/%m/%d/'),
        ),
    ]
