# Generated by Django 4.1 on 2023-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0016_alter_submission_supplementary'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='journal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
