# Generated by Django 4.1 on 2023-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0019_author_paper_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(to='journalApp.author'),
        ),
    ]
