# Generated by Django 4.1 on 2023-06-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0020_remove_paper_authors_paper_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
